// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserCRUD.Infrastructure;

namespace UserCRUD.Infrastructure.Migrations
{
    [DbContext(typeof(UserCRUDDbContext))]
    [Migration("20200114100537_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UserCRUD.Core.Model.UserCRUD.UserCRUD", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthdate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("UserCRUD");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Birthdate = new DateTime(2020, 1, 14, 11, 5, 37, 632, DateTimeKind.Local).AddTicks(2320),
                            Name = "Usuario 1"
                        },
                        new
                        {
                            Id = 2L,
                            Birthdate = new DateTime(2020, 1, 14, 11, 5, 37, 633, DateTimeKind.Local).AddTicks(4202),
                            Name = "Usuario 2"
                        },
                        new
                        {
                            Id = 3L,
                            Birthdate = new DateTime(2020, 1, 14, 11, 5, 37, 633, DateTimeKind.Local).AddTicks(4214),
                            Name = "Usuario 3"
                        },
                        new
                        {
                            Id = 4L,
                            Birthdate = new DateTime(2020, 1, 14, 11, 5, 37, 633, DateTimeKind.Local).AddTicks(4217),
                            Name = "Usuario 4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
